### ISSUE TITLE
Input file validation

### ISSUE THREAD

**Issue by werpuc** [hadexversum/HaDeX#10]
Package function to check what kind of file is uploaded by user and change it if needed (calculate and aggregate).

DynamiX can produce different files - HaDeX should be able to work with all of them.

**Comment by michbur** [comment]
add information about the file type and the file structure

**Comment by michbur** [comment]
read_hdx for .csv and .xls files with data validation

**Comment by werpuc** [comment]
adjust read_hdx() for files from dynamix 2

**Comment by werpuc** [comment]
Currently accepted files are those with csv/xlsx/xls extensions. If the structure of the file is wrong, user is notified.

We're waiting for more example files.
