### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by werpuc** [hadexversum/HaDeX#106]
Things from Julien:

general:
- [x] minimal exchange to zla nazwa bo to brak wymiany a nie minimal
- [x] oni nie maja kontroli in - to te dane z sekwencjonowania i nie umiam obronic czemu my mamy
- [x] powiekszyc linie na plotach 
- [x] pare woodsow kolo siebie 
- [x] opisy przy confidence limit co do czego
- [ ] #123
hybrydowy test:
- [x] kolory hybrydowego zmienic
- [ ] #120
- [x] hide unsignificant 
- [x] volcano - grey na unsignificant
debugowanie:
- [x] wywalaja sie linie przy line+bars na diff butt
- [x] chiclet diff sie wywala czasem, nie wiem czemu niektore plytki sie nie pokazuja 
- [x] obsluga wywalania peptydów jak nie ma powtórzęń do t-testu bo sie caly plik psuje
- [x] małe bars w uc
- [x] kolejnosc aktualizowania parametrow!! wywalic wiele na raz
- [x] wywala sie legenda w chiclecie diff czasem
dołożyć:
- [ ] #122
- [x] opcja 'zaznacz wszystko' do reportu
- [x] w chiclet - protein range!! or uptake range!
- [ ] #124
- [x] nie ma wyboru confidence level w diff uc 
nowości:
- [ ] #125
- [ ] #121

**Comment by werpuc** [comment]
Multiple woods as suggested:

![woods_multiple](https://user-images.githubusercontent.com/9084745/170055776-9c5bf919-629c-49b5-bbfe-f86d1a69cb2d.png)

There could also be this option for comparison plot.
Question: where do we put it?

**Comment by werpuc** [comment]
Do dyskusji: jak ma wyglądać 'hide insinificant' na buterfly i chiclet?

**Comment by michbur** [comment]
hide insignificant for butterfly: remove ribbon, exchange it for uncertainty bars.
