### ISSUE TITLE
Modules for HaDeX

### ISSUE THREAD

**Issue by werpuc** [hadexversum/HaDeX#108]
My proposal for new modules:

- [ ] plot + tooltips + buttons to download (svg, png)
- [ ] plot section + data section
- [ ] test parameters (houde, t test + correction, confidence limit) + hiding parameters
- [ ] sliders for ranges read dynamically + button to adjust to the data
- [ ] adjusting the labels + their sizes
- [ ] types of calculations +time parameters (in, t, out) show when necessary

**Comment by DominikRafacz** [comment]
Transferring it to HaDeX GUI
