### ISSUE TITLE
Charge analysis

### ISSUE THREAD

**Issue by werpuc** [hadexversum/HaDeX#110]
To see how the measurements differ between masses, we propose:

1. mass uptake for different charges and files (distinguished by colors and line types)
2. plot as for replicates but also with charge info.

**Comment by werpuc** [comment]
Ad. 1.
Mass difference (exp_mass - MHP) in time course for chosen peptide (I selected one with multiple charge values). Separately for biological states.
![du](https://user-images.githubusercontent.com/9084745/169523512-2bb98594-26bb-4c27-ab20-b37f6c5cfb07.png)

**Comment by werpuc** [comment]
Ad. 2. 
Mass measured for a peptide in a specific time point with additional information on charge value.
This is the same peptide as in the 
![mass_rep](https://user-images.githubusercontent.com/9084745/169527317-59247a03-9fe1-4727-8276-83a24eab5c21.png)
previous comment, but in 25 mins.

**Comment by werpuc** [comment]
I put the charge info on coverage, and I don't have a strong opinion on that:

For all charges at once:
![cov_z_peptide_all](https://user-images.githubusercontent.com/9084745/169999364-fef0b4f4-b77f-40ab-8ee0-1a81b3ac9eff.png)

Charges separately:
![cov_z_pep_sep](https://user-images.githubusercontent.com/9084745/169999396-67eb7565-5e64-47b3-a49e-f250bf8f79f7.png)

**Comment by michbur** [comment]
Add the 'Charge analysis subpanel'. The first figure presents the average mass change dispersion resulting from the charge variability (x-axis peptide position, y-axis peptide id, fill: mass change dispersion), the second figure is peptide coverage for each peptide separately and the last plot is the mass uptake for individual peptide. The plot with red line will be added to the replicated bar.

**Comment by werpuc** [comment]
Code drafts are [here](https://github.com/hadexversum/exploring_hdx/blob/main/charge_analysis.R). I'll make them into package functions later.
