### ISSUE TITLE
Supplement: deuteration

### ISSUE THREAD

**Issue by mstaniak** [hadexversum/HaDeX#32]
the supplement says:

> After obtaining the mass of the peptide, we can compute the deuteration level depending on the chosen maximum deuteration level. The maximum deuteration can also be computed in two different ways: either as theoretical (where the maximum deuteration depends on the theoretical deuteration levels) and experimental (where the maximum deuteration is assumed to be equal to the deuteration measured at the last time point).
Experimental deuteration level
> The experimental deuteration level is computed as the deuteration level of the peptide from a protein in a specific state and after incubation time 𝑡
compared to the deuteration level measured at the start of the incubation (𝑡0). It yields a value for the chosen state and chosen time 𝑡.

It would be nice to have a formula explaining how exactly we go from from average mass to deuteration, just for the sake of clarity.

**Comment by werpuc** [comment]
This is changed in the new version of the documentation.
