### ISSUE TITLE
Reworking functions in the package to employ data.table and stringi

### ISSUE THREAD

**Issue by werpuc** [hadexversum/HaDeX#43]
All of the existing functions (except for the deprecated ones) should be re-written with data.table and stringi instead of dplyr and stringr. This is also an opportunity to brush up the documentation of each function and provide complete test coverage (aim for the green).
 
The current summary of the situation can be found in the [document](https://docs.google.com/spreadsheets/d/1HZnmNQe1tl13XDNDzCziOe3PMcoDWK4Qq5fFUHfHodQ/edit?usp=sharing).

This issue also covers updates of tests.

**Comment by werpuc** [comment]
Replicate functions added in the package and in the document. Please, merge your branch.

**Comment by michbur** [comment]
Edited description: this issue also covers updates of tests.

**Comment by KrystynaGrzesiak** [comment]
Merge is done. @werpuc helped in defusing all the conflicts peacefully.

**Comment by KrystynaGrzesiak** [comment]
also https://github.com/KrystynaGrzesiak/HaDeX/commit/cbcaac414297f923bc6bca646d2ebe386d387168

**Comment by KrystynaGrzesiak** [comment]
@werpuc rewrites #67 and #72
