### ISSUE TITLE
Update report generation

### ISSUE THREAD

**Issue by werpuc** [hadexversum/HaDeX#56]
At the end of all changes, the report template should be updated to include all new features.

**Comment by werpuc** [comment]
A simple report is completed. The additional messages will be added if needed (not sure now what is necessary). 

To discuss: how to tackle replicate histograms. Should they be in the report? Should their data be visible in the app?

**Comment by michbur** [comment]
The download report screen should include the information on which peptides are selected for a) replicate plot b) deuterium uptake curve plot
