### ISSUE TITLE
expanded documentation of each package function

### ISSUE THREAD

**Issue by werpuc** [hadexversum/HaDeX#66]
All of the package functions should be ticked as well-documented in our [summary](https://docs.google.com/spreadsheets/d/1HZnmNQe1tl13XDNDzCziOe3PMcoDWK4Qq5fFUHfHodQ/edit#gid=0).

**Comment by KrystynaGrzesiak** [comment]
There are some links to old functions names in the documentation. The functions that likely contain some mistakes are marked in the [document](https://docs.google.com/spreadsheets/d/1HZnmNQe1tl13XDNDzCziOe3PMcoDWK4Qq5fFUHfHodQ/edit#gid=0).

**Comment by werpuc** [comment]
All of the documentation is updated and the examples are added. There is an exception for function plot_amino_distribution() that should be rewritten and documentation reconstructed, as a separate issue #67.

The work is finished by now. There may be new comments by @KrystynaGrzesiak during her work on #43 and I will deal with them after the merge. 

Also, the documentation on HaDeXify() is a part of https://github.com/michbur/HaDeX-projects/issues/26.
