### ISSUE TITLE
HaDeX logo on all of the plots

### ISSUE THREAD

**Issue by werpuc** [hadexversum/HaDeX#70]
The HaDeX logo should appear on all of the available plots from the package.

- [ ] plot_amino_distribution
- [x] plot_butterfly
- [x] plot_chiclet
- [x] plot_coverage
- [x] plot_differential
- [x] plot_differential_butterfly
- [x] plot_differential_chiclet
- [x] plot_kinetics
- [x] plot_overlap
- [x] plot_overlap_distribution
- [x] plot_position_frequency
- [x] plot_quality_control
- [x] plot_state_comparison
- [x] plot_volcano
- [x] plot_replicate_histogram
- [x] plot_peptide_mass_measurement
- [x] plot_peptide_charge_measurement

**Comment by KrystynaGrzesiak** [comment]
plot_kinetics HaDeXified ---> https://github.com/KrystynaGrzesiak/HaDeX/commit/c2a6f9d6e40ff507bff39c0b6392998f95bba562

**Comment by KrystynaGrzesiak** [comment]
@werpuc rewrites plot_amino_distribution and HaDeXifies it in #67
