### ISSUE TITLE
Create log files to monitor traffic

### ISSUE THREAD

**Issue by werpuc** [hadexversum/HaDeX#8]
Short log entries to check if tool is used (not by use).

My proposition : when, size file, maybe ip?, if raport was generated

**Comment by werpuc** [comment]
Short log entries to check if tool is used (not by use).

My proposition : when, size file, maybe ip?, if raport was generated

**Comment by michbur** [comment]
Google analytics is sufficient. Check https://shiny.rstudio.com/articles/google-analytics.html
